# Generated by Django 4.2.3 on 2023-11-19 12:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cooking_steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1', models.TextField(max_length=500)),
                ('image_step1', models.ImageField(null=True, upload_to='')),
                ('step2', models.TextField(max_length=500, null=True)),
                ('image_step2', models.ImageField(null=True, upload_to='')),
                ('step3', models.TextField(max_length=500, null=True)),
                ('image_step3', models.ImageField(null=True, upload_to='')),
                ('step4', models.TextField(max_length=500, null=True)),
                ('image_step4', models.ImageField(null=True, upload_to='')),
                ('step5', models.TextField(max_length=500, null=True)),
                ('image_step5', models.ImageField(null=True, upload_to='')),
                ('step6', models.TextField(max_length=500, null=True)),
                ('image_step6', models.ImageField(null=True, upload_to='')),
                ('step7', models.TextField(max_length=500, null=True)),
                ('image_step7', models.ImageField(null=True, upload_to='')),
                ('step8', models.TextField(max_length=500, null=True)),
                ('image_step8', models.ImageField(null=True, upload_to='')),
                ('step9', models.TextField(max_length=500, null=True)),
                ('image_step9', models.ImageField(null=True, upload_to='')),
                ('step10', models.TextField(max_length=500, null=True)),
                ('image_step10', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=400)),
                ('ingredients', models.TextField(max_length=400)),
                ('cooking_time', models.CharField(max_length=40)),
                ('cooking_steps', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='')),
                ('is_visible', models.BooleanField(default=True)),
                ('publishing_date', models.DateField(default=datetime.datetime(2023, 11, 19, 15, 24, 3, 38985))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking_app.category')),
                ('cooking_steps_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooking_app.cooking_steps')),
            ],
        ),
    ]
